# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20180513_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address_zip',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
