# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20180513_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
    ]
