# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_remove_listing_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='prop',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='prop',
            field=models.ForeignKey(db_column='fk_propertyid', default=1, on_delete=django.db.models.deletion.CASCADE, to='realestate.Listing'),
            preserve_default=False,
        ),
    ]
