# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20180513_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureditem',
            name='fkey',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='realestate.Catalog', verbose_name='Featured For Sale'),
        ),
        migrations.AlterField(
            model_name='featureditem',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.CatalogItem'),
        ),
    ]
