# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_catalog_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together=set([('pr2', 'prop')]),
        ),
    ]
