# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20180513_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='furnishing_status',
        ),
        migrations.AddField(
            model_name='listing',
            name='fully_furnished',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
