# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('realestate', '0010_auto_20180513_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=50)),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=50)),
                ('location_country', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='uploads/broker/images')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrokerAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAgencyIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BrokerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=50)),
                ('fkey', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='realestate.Broker', verbose_name='Contact Numbers')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='brokeragency',
            name='fkey',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='realestate.BrokerAgencyIndex'),
        ),
        migrations.AddField(
            model_name='broker',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realestate.BrokerAgency'),
        ),
    ]
