# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_auto_20180515_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brokers',
            field=models.ManyToManyField(to='realestate.Broker'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='realestate.BrokerAgency'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/broker/images'),
        ),
    ]
