# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_auto_20180515_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realestate.Broker')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='brokers',
        ),
        migrations.AddField(
            model_name='listingbroker',
            name='prop',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='realestate.Listing'),
        ),
    ]
