# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20180515_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokercontact',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='brokercontact',
            name='contact_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Phone'), (2, 'Telephone')], default=1),
            preserve_default=False,
        ),
    ]
